# ISSUE pvc in pending state not created ...
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: darwin-volume-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Mi # defined storage for the volume
  storageClassName: default