# Persistent Volume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Mi # defined storage for the volume
  storageClassName: manual

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/d/SAMI/Projects/K8S/data"