apiVersion: apps/v1
kind: Deployment
metadata:
  name: ng
  namespace: ngx
spec:
  selector:
    matchLabels:
      app: ng
  template:
    metadata:
      labels:
        app: ng
    spec:
      containers:
      - name: nginx
        image: ng-web:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

