apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ngx-ingress
  namespace: ngx
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: ngx.minikube.url
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ng-service
            port:
              number: 80