apiVersion: v1
kind: Service
metadata:
  name: ng-service
  namespace: ngx 
spec:
  type: NodePort 
  selector:
    app: ng
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 80 # Container Port
      nodePort: 31879 # NodePort